import 'package:drift/drift.dart';
import '../app_database.dart';

final initialEgyptianMealsSeed = <MealsCompanion>[
  // 1
  const MealsCompanion(
    id: Value(1),
    name: Value('كشري مصري أصلي بالصلصة والدقة'),
    proteinType: Value(ProteinType.legume),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(50),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(true),
  ),
  // 2
  const MealsCompanion(
    id: Value(2),
    name: Value('ملوخية خضراء بالفراخ المحمرة وأرز بالشعرية'),
    proteinType: Value(ProteinType.chicken),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(45),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
  // 3
  const MealsCompanion(
    id: Value(3),
    name: Value('صينية بطاطس باللحمة في الفرن وأرز مصري'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.potato),
    category: Value(MealCategory.ovenBaked),
    prepTime: Value(60),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
  // 4
  const MealsCompanion(
    id: Value(4),
    name: Value('سمك بلطي مشوي بالردة ورز صيادية وسلطة بلدي'),
    proteinType: Value(ProteinType.fish),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.seafood),
    prepTime: Value(40),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(true),
    isFavorite: Value(true),
  ),
  // 5
  const MealsCompanion(
    id: Value(5),
    name: Value('حواوشي بلدي مقرمش في الفرن ومخلل'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.fastFood),
    prepTime: Value(30),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(true),
  ),
  // 6
  const MealsCompanion(
    id: Value(6),
    name: Value('صينية مكرونة بالبشاميل واللحمة المفرومة'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.pasta),
    category: Value(MealCategory.ovenBaked),
    prepTime: Value(65),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
  // 7
  const MealsCompanion(
    id: Value(7),
    name: Value('طاجن بامية باللحمة الضاني وأرز أبيض'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.ovenBaked),
    prepTime: Value(60),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(false),
    isFavorite: Value(false),
  ),
  // 8
  const MealsCompanion(
    id: Value(8),
    name: Value('كبدة إسكندراني بالثوم والفلفل الحامي وعيش بلدي'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.fastFood),
    prepTime: Value(20),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(true),
  ),
  // 9
  const MealsCompanion(
    id: Value(9),
    name: Value('صينية فراخ مشوية بالبصل والبطاطس'),
    proteinType: Value(ProteinType.chicken),
    carbsType: Value(CarbsType.potato),
    category: Value(MealCategory.ovenBaked),
    prepTime: Value(50),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 10
  const MealsCompanion(
    id: Value(10),
    name: Value('مسقعة باللحمة المفرومة والبشاميل وعيش'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(45),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 11
  const MealsCompanion(
    id: Value(11),
    name: Value('شيش طاووق متبل مع أرز بسمتي بالخلطة'),
    proteinType: Value(ProteinType.chicken),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.ovenBaked),
    prepTime: Value(40),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(false),
    isFavorite: Value(false),
  ),
  // 12
  const MealsCompanion(
    id: Value(12),
    name: Value('كفتة حاتي مشوية مع سلطة طحينة وعيش سخن'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(35),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
  // 13
  const MealsCompanion(
    id: Value(13),
    name: Value('سمك فيليه مقلي مع سلطة طحينة وأرز أحمر'),
    proteinType: Value(ProteinType.fish),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.seafood),
    prepTime: Value(30),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 14
  const MealsCompanion(
    id: Value(14),
    name: Value('شوربة عدس أصفر بالشعرية والليمون وعيش محمص'),
    proteinType: Value(ProteinType.legume),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.soupStew),
    prepTime: Value(25),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 15
  const MealsCompanion(
    id: Value(15),
    name: Value('بانيه دجاج ذهبي مقرمش مع مكرونة بالصلصة'),
    proteinType: Value(ProteinType.chicken),
    carbsType: Value(CarbsType.pasta),
    category: Value(MealCategory.fastFood),
    prepTime: Value(30),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(true),
  ),
  // 16
  const MealsCompanion(
    id: Value(16),
    name: Value('طاجن مكرونة بالسجق البلدي زي المحلات'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.pasta),
    category: Value(MealCategory.fastFood),
    prepTime: Value(30),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 17
  const MealsCompanion(
    id: Value(17),
    name: Value('فتة مصرية بالخل والثوم وموزة لحمة مسلوقة'),
    proteinType: Value(ProteinType.beef),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(75),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
  // 18
  const MealsCompanion(
    id: Value(18),
    name: Value('فول مدمس بالزيت الحار وطعمية سخنة وبتنجان مخلل'),
    proteinType: Value(ProteinType.legume),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(15),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 19
  const MealsCompanion(
    id: Value(19),
    name: Value('شكشوكة بالبيض والطماطم والجبنة الرومي وعيش'),
    proteinType: Value(ProteinType.dairy),
    carbsType: Value(CarbsType.bread),
    category: Value(MealCategory.egyptianTraditional),
    prepTime: Value(15),
    isFridaySpecial: Value(false),
    isBudgetFriendly: Value(true),
    isFavorite: Value(false),
  ),
  // 20
  const MealsCompanion(
    id: Value(20),
    name: Value('طاجن جمبري وسبيط بالصوص الأحمر وأرز صيادية'),
    proteinType: Value(ProteinType.fish),
    carbsType: Value(CarbsType.rice),
    category: Value(MealCategory.seafood),
    prepTime: Value(40),
    isFridaySpecial: Value(true),
    isBudgetFriendly: Value(false),
    isFavorite: Value(true),
  ),
];
