// test/support/seed_catalog.dart
// 20 Core Egyptian Starter Dishes as specified in architecture_report.md § 2.4

import 'contracts.dart';

final DateTime seedDate = DateTime(2026, 1, 1);

final List<Meal> initialEgyptianMealsSeed = [
  Meal(
    id: 1,
    name: 'كشري مصري أصلي بالصلصة والدقة',
    proteinType: ProteinType.legume,
    carbsType: CarbsType.rice,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 50,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 2,
    name: 'ملوخية خضراء بالفراخ المحمرة وأرز بالشعرية',
    proteinType: ProteinType.chicken,
    carbsType: CarbsType.rice,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 45,
    isFridaySpecial: false,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 3,
    name: 'صينية بطاطس باللحمة في الفرن وأرز مصري',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.potato,
    category: MealCategory.ovenBaked,
    prepTimeMinutes: 60,
    isFridaySpecial: false,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 4,
    name: 'سمك بلطي مشوي بالردة ورز صيادية وسلطة بلدي',
    proteinType: ProteinType.fish,
    carbsType: CarbsType.rice,
    category: MealCategory.seafood,
    prepTimeMinutes: 40,
    isFridaySpecial: true,
    isBudgetFriendly: true,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 5,
    name: 'حواوشي بلدي مقرمش في الفرن ومخلل',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.bread,
    category: MealCategory.fastFood,
    prepTimeMinutes: 30,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 6,
    name: 'صينية مكرونة بالبشاميل واللحمة المفرومة',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.pasta,
    category: MealCategory.ovenBaked,
    prepTimeMinutes: 65,
    isFridaySpecial: true,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 7,
    name: 'طاجن بامية باللحمة الضاني وأرز أبيض',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.rice,
    category: MealCategory.ovenBaked,
    prepTimeMinutes: 60,
    isFridaySpecial: false,
    isBudgetFriendly: false,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 8,
    name: 'كبدة إسكندراني بالثوم والفلفل الحامي وعيش بلدي',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.bread,
    category: MealCategory.fastFood,
    prepTimeMinutes: 20,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 9,
    name: 'صينية فراخ مشوية بالبصل والبطاطس',
    proteinType: ProteinType.chicken,
    carbsType: CarbsType.potato,
    category: MealCategory.ovenBaked,
    prepTimeMinutes: 50,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 10,
    name: 'مسقعة باللحمة المفرومة والبشاميل وعيش',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.bread,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 45,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 11,
    name: 'شيش طاووق متبل مع أرز بسمتي بالخلطة',
    proteinType: ProteinType.chicken,
    carbsType: CarbsType.rice,
    category: MealCategory.ovenBaked,
    prepTimeMinutes: 40,
    isFridaySpecial: false,
    isBudgetFriendly: false,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 12,
    name: 'كفتة حاتي مشوية مع سلطة طحينة وعيش سخن',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.bread,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 35,
    isFridaySpecial: true,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 13,
    name: 'سمك فيليه مقلي مع سلطة طحينة وأرز أحمر',
    proteinType: ProteinType.fish,
    carbsType: CarbsType.rice,
    category: MealCategory.seafood,
    prepTimeMinutes: 30,
    isFridaySpecial: true,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 14,
    name: 'شوربة عدس أصفر بالشعرية والليمون وعيش محمص',
    proteinType: ProteinType.legume,
    carbsType: CarbsType.bread,
    category: MealCategory.soupStew,
    prepTimeMinutes: 25,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 15,
    name: 'بانيه دجاج ذهبي مقرمش مع مكرونة بالصلصة',
    proteinType: ProteinType.chicken,
    carbsType: CarbsType.pasta,
    category: MealCategory.fastFood,
    prepTimeMinutes: 30,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 16,
    name: 'طاجن مكرونة بالسجق البلدي زي المحلات',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.pasta,
    category: MealCategory.fastFood,
    prepTimeMinutes: 30,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 17,
    name: 'فتة مصرية بالخل والثوم وموزة لحمة مسلوقة',
    proteinType: ProteinType.beef,
    carbsType: CarbsType.rice,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 75,
    isFridaySpecial: true,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
  Meal(
    id: 18,
    name: 'فول مدمس بالزيت الحار وطعمية سخنة وبتنجان مخلل',
    proteinType: ProteinType.legume,
    carbsType: CarbsType.bread,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 15,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 19,
    name: 'شكشوكة بالبيض والطماطم والجبنة الرومي وعيش',
    proteinType: ProteinType.dairy,
    carbsType: CarbsType.bread,
    category: MealCategory.egyptianTraditional,
    prepTimeMinutes: 15,
    isFridaySpecial: false,
    isBudgetFriendly: true,
    isFavorite: false,
    createdAt: seedDate,
  ),
  Meal(
    id: 20,
    name: 'طاجن جمبري وسبيط بالصوص الأحمر وأرز صيادية',
    proteinType: ProteinType.fish,
    carbsType: CarbsType.rice,
    category: MealCategory.seafood,
    prepTimeMinutes: 40,
    isFridaySpecial: true,
    isBudgetFriendly: false,
    isFavorite: true,
    createdAt: seedDate,
  ),
];
